apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configurations
  template:
    metadata:
      labels:
        app: configurations
    spec:
      containers:
      - imagePullPolicy: Never
        image: configurations
        name: configurations
        envFrom:
        - secretRef:
            name: configurations
      restartPolicy: Always
      imagePullSecrets:
      - name: acr-secret
status: {}